name: Spring Boot Demo CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "target/EC2DeployDemo-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"

      - name: Deploy and Restart Service on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user

            # Ensure the JAR is executable
            chmod +x EC2DeployDemo-0.0.1-SNAPSHOT.jar

            # Stop the service if it exists
            if systemctl list-units --full -all | grep -Fq "ec2deploydemo.service"; then
              sudo systemctl stop ec2deploydemo.service
            fi

            # Create systemd service file
            echo "[Unit]
            Description=Spring Boot Demo App
            After=network.target

            [Service]
            User=ec2-user
            WorkingDirectory=/home/ec2-user
            ExecStart=/usr/bin/java -jar /home/ec2-user/EC2DeployDemo-0.0.1-SNAPSHOT.jar
            SuccessExitStatus=143
            Restart=always
            RestartSec=10

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/ec2deploydemo.service

            # Reload systemd, enable and restart the service
            sudo systemctl daemon-reload
            sudo systemctl enable ec2deploydemo.service
            sudo systemctl restart ec2deploydemo.service
