name: Spring Boot Demo CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "target/EC2DeployDemo-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"
      
      - name: Run App on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user
            pkill -f 'EC2DeployDemo-0.0.1-SNAPSHOT' || true
            chmod +x EC2DeployDemo-0.0.1-SNAPSHOT.jar
            nohup java -jar EC2DeployDemo-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
    

