name: Spring Boot Demo CI/CD

on:
  push:
    branches: ["master]

Jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

       - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'EC2DeployDemo-0.0.1-SNAPSHOT' || true
            cd /home/ec2-user
            rm -f EC2DeployDemo-0.0.1-SNAPSHOT.jar
            scp target/*.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/EC2DeployDemo-0.0.1-SNAPSHOT.jar
            nohup java -jar EC2DeployDemo-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
    

